// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "aeonia_types.hpp"
#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_aphids_ptr
SEXP make_aphids_ptr(const double& K, const double& K_p, const double& pseudo_surv, const double& pred_surv, const double& extinct_N, const bool& demog_error, const double& sigma_x, const double& rho, const double& fly_p, const arma::vec& attack_surv, const std::string& aphid_name, const arma::cube& leslie_mat, const arma::mat& aphid_density_0, const double& alate_b0, const double& alate_b1, const uint32& adult_age, const uint32& living_days);
RcppExport SEXP _aeonia_make_aphids_ptr(SEXP KSEXP, SEXP K_pSEXP, SEXP pseudo_survSEXP, SEXP pred_survSEXP, SEXP extinct_NSEXP, SEXP demog_errorSEXP, SEXP sigma_xSEXP, SEXP rhoSEXP, SEXP fly_pSEXP, SEXP attack_survSEXP, SEXP aphid_nameSEXP, SEXP leslie_matSEXP, SEXP aphid_density_0SEXP, SEXP alate_b0SEXP, SEXP alate_b1SEXP, SEXP adult_ageSEXP, SEXP living_daysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const double& >::type K_p(K_pSEXP);
    Rcpp::traits::input_parameter< const double& >::type pseudo_surv(pseudo_survSEXP);
    Rcpp::traits::input_parameter< const double& >::type pred_surv(pred_survSEXP);
    Rcpp::traits::input_parameter< const double& >::type extinct_N(extinct_NSEXP);
    Rcpp::traits::input_parameter< const bool& >::type demog_error(demog_errorSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma_x(sigma_xSEXP);
    Rcpp::traits::input_parameter< const double& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double& >::type fly_p(fly_pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type attack_surv(attack_survSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type aphid_name(aphid_nameSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type leslie_mat(leslie_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aphid_density_0(aphid_density_0SEXP);
    Rcpp::traits::input_parameter< const double& >::type alate_b0(alate_b0SEXP);
    Rcpp::traits::input_parameter< const double& >::type alate_b1(alate_b1SEXP);
    Rcpp::traits::input_parameter< const uint32& >::type adult_age(adult_ageSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type living_days(living_daysSEXP);
    rcpp_result_gen = Rcpp::wrap(make_aphids_ptr(K, K_p, pseudo_surv, pred_surv, extinct_N, demog_error, sigma_x, rho, fly_p, attack_surv, aphid_name, leslie_mat, aphid_density_0, alate_b0, alate_b1, adult_age, living_days));
    return rcpp_result_gen;
END_RCPP
}
// get_aphid_n_age_stages
uint32 get_aphid_n_age_stages(SEXP aphid_ptr);
RcppExport SEXP _aeonia_get_aphid_n_age_stages(SEXP aphid_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type aphid_ptr(aphid_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_aphid_n_age_stages(aphid_ptr));
    return rcpp_result_gen;
END_RCPP
}
// get_apterous_leslie
arma::mat get_apterous_leslie(SEXP aphid_ptr);
RcppExport SEXP _aeonia_get_apterous_leslie(SEXP aphid_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type aphid_ptr(aphid_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_apterous_leslie(aphid_ptr));
    return rcpp_result_gen;
END_RCPP
}
// get_carrying_capacity
NumericVector get_carrying_capacity(const arma::mat& L, const NumericVector& K, const NumericVector& pseudo_surv, const NumericVector& pred_surv);
RcppExport SEXP _aeonia_get_carrying_capacity(SEXP LSEXP, SEXP KSEXP, SEXP pseudo_survSEXP, SEXP pred_survSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pseudo_surv(pseudo_survSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type pred_surv(pred_survSEXP);
    rcpp_result_gen = Rcpp::wrap(get_carrying_capacity(L, K, pseudo_surv, pred_surv));
    return rcpp_result_gen;
END_RCPP
}
// alate_prop
NumericVector alate_prop(const NumericVector& z, const double& alate_b0, const double& alate_b1);
RcppExport SEXP _aeonia_alate_prop(SEXP zSEXP, SEXP alate_b0SEXP, SEXP alate_b1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const double& >::type alate_b0(alate_b0SEXP);
    Rcpp::traits::input_parameter< const double& >::type alate_b1(alate_b1SEXP);
    rcpp_result_gen = Rcpp::wrap(alate_prop(z, alate_b0, alate_b1));
    return rcpp_result_gen;
END_RCPP
}
// make_insects_ptr_cpp
SEXP make_insects_ptr_cpp(SEXP aphids_xptr, SEXP wasps_xptr, SEXP mummies_xptr);
RcppExport SEXP _aeonia_make_insects_ptr_cpp(SEXP aphids_xptrSEXP, SEXP wasps_xptrSEXP, SEXP mummies_xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type aphids_xptr(aphids_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type wasps_xptr(wasps_xptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mummies_xptr(mummies_xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(make_insects_ptr_cpp(aphids_xptr, wasps_xptr, mummies_xptr));
    return rcpp_result_gen;
END_RCPP
}
// get_aphid_X0
arma::vec get_aphid_X0(SEXP insects_ptr);
RcppExport SEXP _aeonia_get_aphid_X0(SEXP insects_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type insects_ptr(insects_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(get_aphid_X0(insects_ptr));
    return rcpp_result_gen;
END_RCPP
}
// test_insect_pops
DataFrame test_insect_pops(const uint32& max_t, const double& N0, const double& W0, const double& M0, const double& Y0, SEXP insects_ptr);
RcppExport SEXP _aeonia_test_insect_pops(SEXP max_tSEXP, SEXP N0SEXP, SEXP W0SEXP, SEXP M0SEXP, SEXP Y0SEXP, SEXP insects_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32& >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< const double& >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< const double& >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< const double& >::type M0(M0SEXP);
    Rcpp::traits::input_parameter< const double& >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type insects_ptr(insects_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(test_insect_pops(max_t, N0, W0, M0, Y0, insects_ptr));
    return rcpp_result_gen;
END_RCPP
}
// logit
NumericVector logit(NumericVector p);
RcppExport SEXP _aeonia_logit(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(logit(p));
    return rcpp_result_gen;
END_RCPP
}
// inv_logit
NumericVector inv_logit(NumericVector a);
RcppExport SEXP _aeonia_inv_logit(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_logit(a));
    return rcpp_result_gen;
END_RCPP
}
// sad_leslie
NumericVector sad_leslie(arma::mat L);
RcppExport SEXP _aeonia_sad_leslie(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(sad_leslie(L));
    return rcpp_result_gen;
END_RCPP
}
// leslie_matrix
NumericMatrix leslie_matrix(IntegerVector instar_days, const double& surv_juv, NumericVector surv_adult, NumericVector repro);
RcppExport SEXP _aeonia_leslie_matrix(SEXP instar_daysSEXP, SEXP surv_juvSEXP, SEXP surv_adultSEXP, SEXP reproSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type instar_days(instar_daysSEXP);
    Rcpp::traits::input_parameter< const double& >::type surv_juv(surv_juvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type surv_adult(surv_adultSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type repro(reproSEXP);
    rcpp_result_gen = Rcpp::wrap(leslie_matrix(instar_days, surv_juv, surv_adult, repro));
    return rcpp_result_gen;
END_RCPP
}
// col_namer
CharacterVector col_namer(const std::string& summ, const bool& out_pseudo, const bool& out_attack_surv, const std::string& out_stages, const uint32& n_age_stages);
RcppExport SEXP _aeonia_col_namer(SEXP summSEXP, SEXP out_pseudoSEXP, SEXP out_attack_survSEXP, SEXP out_stagesSEXP, SEXP n_age_stagesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type summ(summSEXP);
    Rcpp::traits::input_parameter< const bool& >::type out_pseudo(out_pseudoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type out_attack_surv(out_attack_survSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_stages(out_stagesSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_age_stages(n_age_stagesSEXP);
    rcpp_result_gen = Rcpp::wrap(col_namer(summ, out_pseudo, out_attack_surv, out_stages, n_age_stages));
    return rcpp_result_gen;
END_RCPP
}
// make_disease_ptr
SEXP make_disease_ptr(const double& radius, const double& virus_attract, const double& pseudo_repel, const double& p_load_alate, const double& p_load_plant, const double& epsilon, const double& w, const uint32& total_exp_days);
RcppExport SEXP _aeonia_make_disease_ptr(SEXP radiusSEXP, SEXP virus_attractSEXP, SEXP pseudo_repelSEXP, SEXP p_load_alateSEXP, SEXP p_load_plantSEXP, SEXP epsilonSEXP, SEXP wSEXP, SEXP total_exp_daysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< const double& >::type virus_attract(virus_attractSEXP);
    Rcpp::traits::input_parameter< const double& >::type pseudo_repel(pseudo_repelSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_load_alate(p_load_alateSEXP);
    Rcpp::traits::input_parameter< const double& >::type p_load_plant(p_load_plantSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const double& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type total_exp_days(total_exp_daysSEXP);
    rcpp_result_gen = Rcpp::wrap(make_disease_ptr(radius, virus_attract, pseudo_repel, p_load_alate, p_load_plant, epsilon, w, total_exp_days));
    return rcpp_result_gen;
END_RCPP
}
// sim_plantscape
DataFrame sim_plantscape(const arma::ucube& landscapes, arma::cube N0, arma::cube W0, arma::cube M0, arma::vec Y0, SEXP insect_ptr, SEXP disease_ptr, Nullable<NumericMatrix> wasp_plant_attract, const uint32& max_t, const std::string& summ, uint32 infect_time_n, const double& aphid_gone_thresh, const double& wasp_gone_thresh, const bool& infect_stop, const bool& out_pseudo, const bool& out_attack_surv, const std::string& out_stages, const std::string& out_dispersals, const bool& show_progress, uint32 n_threads);
RcppExport SEXP _aeonia_sim_plantscape(SEXP landscapesSEXP, SEXP N0SEXP, SEXP W0SEXP, SEXP M0SEXP, SEXP Y0SEXP, SEXP insect_ptrSEXP, SEXP disease_ptrSEXP, SEXP wasp_plant_attractSEXP, SEXP max_tSEXP, SEXP summSEXP, SEXP infect_time_nSEXP, SEXP aphid_gone_threshSEXP, SEXP wasp_gone_threshSEXP, SEXP infect_stopSEXP, SEXP out_pseudoSEXP, SEXP out_attack_survSEXP, SEXP out_stagesSEXP, SEXP out_dispersalsSEXP, SEXP show_progressSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ucube& >::type landscapes(landscapesSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type W0(W0SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type M0(M0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y0(Y0SEXP);
    Rcpp::traits::input_parameter< SEXP >::type insect_ptr(insect_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type disease_ptr(disease_ptrSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type wasp_plant_attract(wasp_plant_attractSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type summ(summSEXP);
    Rcpp::traits::input_parameter< uint32 >::type infect_time_n(infect_time_nSEXP);
    Rcpp::traits::input_parameter< const double& >::type aphid_gone_thresh(aphid_gone_threshSEXP);
    Rcpp::traits::input_parameter< const double& >::type wasp_gone_thresh(wasp_gone_threshSEXP);
    Rcpp::traits::input_parameter< const bool& >::type infect_stop(infect_stopSEXP);
    Rcpp::traits::input_parameter< const bool& >::type out_pseudo(out_pseudoSEXP);
    Rcpp::traits::input_parameter< const bool& >::type out_attack_surv(out_attack_survSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_stages(out_stagesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_dispersals(out_dispersalsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type show_progress(show_progressSEXP);
    Rcpp::traits::input_parameter< uint32 >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_plantscape(landscapes, N0, W0, M0, Y0, insect_ptr, disease_ptr, wasp_plant_attract, max_t, summ, infect_time_n, aphid_gone_thresh, wasp_gone_thresh, infect_stop, out_pseudo, out_attack_surv, out_stages, out_dispersals, show_progress, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// sim_plant_types
arma::ucube sim_plant_types(const uint32& n_x, const uint32& n_y, const uint32& n_virus, const uint32& n_pseudo, const double& wt_vp, const double& wt_pv, const double& wt_vv, const double& wt_pp, const uint32& n_lands, Nullable<IntegerMatrix> virus_starts, Nullable<IntegerMatrix> pseudo_starts, const bool& show_progress, uint32 n_threads);
RcppExport SEXP _aeonia_sim_plant_types(SEXP n_xSEXP, SEXP n_ySEXP, SEXP n_virusSEXP, SEXP n_pseudoSEXP, SEXP wt_vpSEXP, SEXP wt_pvSEXP, SEXP wt_vvSEXP, SEXP wt_ppSEXP, SEXP n_landsSEXP, SEXP virus_startsSEXP, SEXP pseudo_startsSEXP, SEXP show_progressSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32& >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_virus(n_virusSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_pseudo(n_pseudoSEXP);
    Rcpp::traits::input_parameter< const double& >::type wt_vp(wt_vpSEXP);
    Rcpp::traits::input_parameter< const double& >::type wt_pv(wt_pvSEXP);
    Rcpp::traits::input_parameter< const double& >::type wt_vv(wt_vvSEXP);
    Rcpp::traits::input_parameter< const double& >::type wt_pp(wt_ppSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_lands(n_landsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type virus_starts(virus_startsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type pseudo_starts(pseudo_startsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type show_progress(show_progressSEXP);
    Rcpp::traits::input_parameter< uint32 >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_plant_types(n_x, n_y, n_virus, n_pseudo, wt_vp, wt_pv, wt_vv, wt_pp, n_lands, virus_starts, pseudo_starts, show_progress, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// land_cube2list
List land_cube2list(const arma::icube& land_cube);
RcppExport SEXP _aeonia_land_cube2list(SEXP land_cubeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::icube& >::type land_cube(land_cubeSEXP);
    rcpp_result_gen = Rcpp::wrap(land_cube2list(land_cube));
    return rcpp_result_gen;
END_RCPP
}
// booter
NumericVector booter(const arma::vec& x, const int32& B, const double& alpha);
RcppExport SEXP _aeonia_booter(SEXP xSEXP, SEXP BSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int32& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(booter(x, B, alpha));
    return rcpp_result_gen;
END_RCPP
}
// make_wasps_ptr
SEXP make_wasps_ptr(const arma::vec& rel_attack, const double& a, const double& k, const double& h, const double& sex_ratio, const double& s_y, const double& zeta, const double& sigma_y, const bool& demog_error);
RcppExport SEXP _aeonia_make_wasps_ptr(SEXP rel_attackSEXP, SEXP aSEXP, SEXP kSEXP, SEXP hSEXP, SEXP sex_ratioSEXP, SEXP s_ySEXP, SEXP zetaSEXP, SEXP sigma_ySEXP, SEXP demog_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type rel_attack(rel_attackSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double& >::type sex_ratio(sex_ratioSEXP);
    Rcpp::traits::input_parameter< const double& >::type s_y(s_ySEXP);
    Rcpp::traits::input_parameter< const double& >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma_y(sigma_ySEXP);
    Rcpp::traits::input_parameter< const bool& >::type demog_error(demog_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(make_wasps_ptr(rel_attack, a, k, h, sex_ratio, s_y, zeta, sigma_y, demog_error));
    return rcpp_result_gen;
END_RCPP
}
// make_mummies_ptr
SEXP make_mummies_ptr(const double& pred_surv, const double& mummy_smooth, const double& extinct_N, const uint32& mummy_dev_time);
RcppExport SEXP _aeonia_make_mummies_ptr(SEXP pred_survSEXP, SEXP mummy_smoothSEXP, SEXP extinct_NSEXP, SEXP mummy_dev_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type pred_surv(pred_survSEXP);
    Rcpp::traits::input_parameter< const double& >::type mummy_smooth(mummy_smoothSEXP);
    Rcpp::traits::input_parameter< const double& >::type extinct_N(extinct_NSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type mummy_dev_time(mummy_dev_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(make_mummies_ptr(pred_surv, mummy_smooth, extinct_N, mummy_dev_time));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aeonia_make_aphids_ptr", (DL_FUNC) &_aeonia_make_aphids_ptr, 17},
    {"_aeonia_get_aphid_n_age_stages", (DL_FUNC) &_aeonia_get_aphid_n_age_stages, 1},
    {"_aeonia_get_apterous_leslie", (DL_FUNC) &_aeonia_get_apterous_leslie, 1},
    {"_aeonia_get_carrying_capacity", (DL_FUNC) &_aeonia_get_carrying_capacity, 4},
    {"_aeonia_alate_prop", (DL_FUNC) &_aeonia_alate_prop, 3},
    {"_aeonia_make_insects_ptr_cpp", (DL_FUNC) &_aeonia_make_insects_ptr_cpp, 3},
    {"_aeonia_get_aphid_X0", (DL_FUNC) &_aeonia_get_aphid_X0, 1},
    {"_aeonia_test_insect_pops", (DL_FUNC) &_aeonia_test_insect_pops, 6},
    {"_aeonia_logit", (DL_FUNC) &_aeonia_logit, 1},
    {"_aeonia_inv_logit", (DL_FUNC) &_aeonia_inv_logit, 1},
    {"_aeonia_sad_leslie", (DL_FUNC) &_aeonia_sad_leslie, 1},
    {"_aeonia_leslie_matrix", (DL_FUNC) &_aeonia_leslie_matrix, 4},
    {"_aeonia_col_namer", (DL_FUNC) &_aeonia_col_namer, 5},
    {"_aeonia_make_disease_ptr", (DL_FUNC) &_aeonia_make_disease_ptr, 8},
    {"_aeonia_sim_plantscape", (DL_FUNC) &_aeonia_sim_plantscape, 20},
    {"_aeonia_sim_plant_types", (DL_FUNC) &_aeonia_sim_plant_types, 13},
    {"_aeonia_land_cube2list", (DL_FUNC) &_aeonia_land_cube2list, 1},
    {"_aeonia_booter", (DL_FUNC) &_aeonia_booter, 3},
    {"_aeonia_make_wasps_ptr", (DL_FUNC) &_aeonia_make_wasps_ptr, 9},
    {"_aeonia_make_mummies_ptr", (DL_FUNC) &_aeonia_make_mummies_ptr, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_aeonia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
