// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "aeonia_types.hpp"
#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// landscape_sims
arma::ucube landscape_sims(const uint32& n_x, const uint32& n_y, const arma::mat& wt_mat, const uint32& n_virus, const uint32& n_pseudo, const uint32& n_lands, const bool& show_progress, uint32 n_threads);
RcppExport SEXP _aeonia_landscape_sims(SEXP n_xSEXP, SEXP n_ySEXP, SEXP wt_matSEXP, SEXP n_virusSEXP, SEXP n_pseudoSEXP, SEXP n_landsSEXP, SEXP show_progressSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint32& >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type wt_mat(wt_matSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_virus(n_virusSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_pseudo(n_pseudoSEXP);
    Rcpp::traits::input_parameter< const uint32& >::type n_lands(n_landsSEXP);
    Rcpp::traits::input_parameter< const bool& >::type show_progress(show_progressSEXP);
    Rcpp::traits::input_parameter< uint32 >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_sims(n_x, n_y, wt_mat, n_virus, n_pseudo, n_lands, show_progress, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// landscape_list
List landscape_list(const arma::ucube& land_cube);
RcppExport SEXP _aeonia_landscape_list(SEXP land_cubeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::ucube& >::type land_cube(land_cubeSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_list(land_cube));
    return rcpp_result_gen;
END_RCPP
}
// logit
NumericVector logit(NumericVector p);
RcppExport SEXP _aeonia_logit(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(logit(p));
    return rcpp_result_gen;
END_RCPP
}
// inv_logit
NumericVector inv_logit(NumericVector a);
RcppExport SEXP _aeonia_inv_logit(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_logit(a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aeonia_landscape_sims", (DL_FUNC) &_aeonia_landscape_sims, 8},
    {"_aeonia_landscape_list", (DL_FUNC) &_aeonia_landscape_list, 1},
    {"_aeonia_logit", (DL_FUNC) &_aeonia_logit, 1},
    {"_aeonia_inv_logit", (DL_FUNC) &_aeonia_inv_logit, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_aeonia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
