# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_aphids_ptr <- function(K, K_p, pseudo_surv, pred_surv, extinct_N, demog_error, sigma_x, rho, fly_p, attack_surv, aphid_name, leslie_mat, aphid_density_0, alate_b0, alate_b1, adult_age, living_days) {
    .Call(`_aeonia_make_aphids_ptr`, K, K_p, pseudo_surv, pred_surv, extinct_N, demog_error, sigma_x, rho, fly_p, attack_surv, aphid_name, leslie_mat, aphid_density_0, alate_b0, alate_b1, adult_age, living_days)
}

get_aphid_n_age_stages <- function(aphid_ptr) {
    .Call(`_aeonia_get_aphid_n_age_stages`, aphid_ptr)
}

get_apterous_leslie <- function(aphid_ptr) {
    .Call(`_aeonia_get_apterous_leslie`, aphid_ptr)
}

get_carrying_capacity <- function(L, K, pseudo_surv, pred_surv) {
    .Call(`_aeonia_get_carrying_capacity`, L, K, pseudo_surv, pred_surv)
}

#' Calculate the proportion of offspring that are alates.
#'
#' @param z Numeric vector of total aphid abundances (including non-winged,
#'     winged, and parasitized).
#' @inheritParams make_insects_ptr
#'
#' @export
#'
alate_prop <- function(z, alate_b0 = -5, alate_b1 = 0.0022) {
    .Call(`_aeonia_alate_prop`, z, alate_b0, alate_b1)
}

make_insects_ptr_cpp <- function(aphids_xptr, wasps_xptr, mummies_xptr) {
    .Call(`_aeonia_make_insects_ptr_cpp`, aphids_xptr, wasps_xptr, mummies_xptr)
}

get_aphid_X0 <- function(insects_ptr) {
    .Call(`_aeonia_get_aphid_X0`, insects_ptr)
}

#' Test population dynamics for insects for a set of parameters.
#'
#' This function is just for one plant, so the probability that an
#' alate leaves the plant (argument `fly_p` in [make_insects_ptr()]) is always 1.
#'
#' @inheritParams sim_plantscape
#'
#' @export
#'
test_insect_pops <- function(max_t, N0, W0, M0, Y0, insects_ptr) {
    .Call(`_aeonia_test_insect_pops`, max_t, N0, W0, M0, Y0, insects_ptr)
}

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_aeonia_logit`, p)
}

#' @rdname logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_aeonia_inv_logit`, a)
}

#' Compute stable age distribution from transition matrix.
#'
#' The stable age distribution is the proportion of different stages that
#' is required for the population to grow exponentially.
#'
#' @param L Numeric transition matrix. Must be square.
#'
#' @export
#'
sad_leslie <- function(L) {
    .Call(`_aeonia_sad_leslie`, L)
}

leslie_matrix <- function(instar_days, surv_juv, surv_adult, repro) {
    .Call(`_aeonia_leslie_matrix`, instar_days, surv_juv, surv_adult, repro)
}

#' Just create column names, for use in R.
#'
#' @inheritParams sim_plantscape
#'
#' @export
#'
col_namer <- function(summ, out_pseudo, out_attack_surv, out_stages, n_age_stages = 29L) {
    .Call(`_aeonia_col_namer`, summ, out_pseudo, out_attack_surv, out_stages, n_age_stages)
}

#' Create a pointer object in which to store disease (and dispersal) info.
#'
#' This pointer is used as an argument to [sim_plantscape()].
#'
#' @details # Radius
#' From "The Role of Aphid Behaviour in the Epidemiology of Potato Virus Y:
#' a Simulation Study" by Thomas Nemecek (1993; p. 72), dispersal distances
#' follow a Weibull distribution with shape = 0.6569 and scale = 9.613.
#'
#' For use in larger landscapes, the object `pop_info$radius` is the median
#' of this distribution.
#' See `raw-data/pop_info.R` for the code used to generate it.
#'
#' For smaller landscapes (e.g., 3x3), I use `radius = 1`.
#'
#' @param n_x Single integer indicating x dimension of the landscape.
#'     Must be at least `2` and less than `1e6`.
#' @param n_y Single integer indicating y dimension of the landscape.
#'     Must be at least `2` and less than `1e6`.
#' @param radius Max distance that alates will travel between plants.
#'     Must be >= 1.
#'     See "Radius" section below for details.
#' @param virus_attract Effect of virus infection on alate alighting.
#'     Sampling weights for virus-infectious plants is `virus_attract`,
#'     compared to empty (no virus or *Pseudomonas*) plants whose weight is 1.
#'     Thus, when `virus_attract > 1`, alates are attracted to virus-infectious
#'     plants, while `virus_attract < 1` causes them to be repelled by
#'     virus-infectious plants.
#'     Values must be `> 0`.
#' @param pseudo_repel Effect of *Pseudomonas* infection on alate alighting.
#'     Sampling weights for *Pseudomonas*-containing plants is
#'     `1 / pseudo_repel` (note difference from `virus_attract`, hence the
#'     different names!), compared to empty (no virus or *Pseudomonas*)
#'     plants whose weight is 1.
#'     Thus, when `pseudo_repel > 1`, alates are repelled by
#'     *Pseudomonas*-containing plants,
#'     while `pseudo_repel < 1` causes them to be attracted to
#'     *Pseudomonas*-containing plants.
#'     Values must be `> 0`.
#' @param p_load_alate Single numeric indicating the probability that an
#'     uninoculated alate is loaded with a virus if it interacts with an
#'     inoculated plant.
#' @param p_load_plant Single numeric indicating the probability that an
#'     uninoculated plant is loaded with a virus if it interacts with an
#'     inoculated alate.
#' @param epsilon Effect of virus infection on alate acceptance.
#'     Values `> 1` cause alates to be more likely to stay and feed
#'     (indefinitely) on virus-infected plants,
#'     while values `< 1` cause them to be less likely to stay and feed on
#'     virus-infected plants.
#'     Values must be `> 0`, and `epsilon * w` must be `< 1`.
#'     Defaults to `1`.
#' @param w Probability that an alate accepts a plant, meaning that
#'     it stays to feed on it indefinitely.
#'     Must be `> 1e-4` and `< 1`.
#'     The lower limit is because a very small value of `w` causes alates to
#'     fly to so many plants that it becomes computationally problematic.
#'     This is the same reason that I check for (and return and error) if
#'     `w*epsilon < 1e-4`.
#'     Defaults to `0.2`.
#' @param total_exp_days Single integer indicating the number of days required
#'     for a plant to transition from exposed (inoculated with virus but
#'     not able to pass it on) to infectious (able to infect other plants).
#'     A value of `0` means that an alate inoculating a plant causes that
#'     plant to be infectious the same day.
#'     Because this is not realistic and computationally troublesome,
#'     only values `>1` are allowed.
#'     Defaults to `7`, which is based on the paper "Cucumber mosaic virus
#'     isolates seedborne in *Phaseolus vulgaris*: serology, host-pathogen
#'     relationships, and seed transmission" (Davis & Hampton, 1986).
#'
#'
#' @return An `externalptr` object that points to a C++ object that can
#' be passed to [sim_plantscape()].
#'
#' @export
#'
make_disease_ptr <- function(radius, virus_attract, pseudo_repel, p_load_alate, p_load_plant, epsilon = 1, w = 0.2, total_exp_days = 7L) {
    .Call(`_aeonia_make_disease_ptr`, radius, virus_attract, pseudo_repel, p_load_alate, p_load_plant, epsilon, w, total_exp_days)
}

#' Simulation plant landscapes with virus spread.
#'
#' @details # Summarizing
#' If `summ == "none"`, `n_x * n_y` rows are output for each rep and time point.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `time`: time point
#' 3.  `x`: plant x coordinate
#' 4.  `y`: plant y coordinate
#' 5.  `pseudo`: plant contains *Pseudomonas* (0 or 1); note: this column isn't
#'     included if `out_pseudo = FALSE`
#' 6.  `virus`: plant infectious with virus (0 or 1)
#' 7.  `aphids`: aphid (non-winged) density
#' 8.  `alates`: alate density
#' 9.  `parasitized`: parasitized aphid density
#' 10. `mummies`: mummy density
#' 11. `wasps`: total parasitoid density (`x` and `y` for this row will be 0)
#'
#'
#' If `summ == "time"`, one row is output per rep and time point.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `time`: time point
#' 3. `virus`: number of plants infectious with virus
#' 4. `aphids`: total aphid (non-winged) density summed across all plants
#' 5. `alates`: total alate density summed across all plants
#' 6. `parasitized`: total parasitized aphid density summed across all plants
#' 7. `mummies`: total mummy density summed across all plants
#' 8. `wasps` total parasitoid density
#'
#' If `summ == "all"`, one row is output per rep.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `p_alates`: mean total alates / total aphids
#' 3.  `log_aphids`: mean log(aphids+1)
#' 4.  `aphids`: mean aphids
#' 5.  `log_alates`: mean log(alates+1)
#' 6.  `alates`: mean alates
#' 7.  `log_alates`: mean log(parasitized aphids+1)
#' 8.  `alates`: mean parasitized aphids
#' 9.  `log_mummies`: mean log(mummies+1)
#' 10. `mummies`: mean mummies
#' 11. `log_wasps`: mean log(wasps+1)
#' 12. `wasps`: mean wasps
#' 13. `infect_time`: time it took to have `infect_time_n` plants infected
#' 14. `n_infected`: maximum number of plants infected with virus
#'
#'
#'
#'
#' @param landscapes Integer cube with the types of each plant in each
#'     landscape. It's assumed that rows are x the dimension,
#'     columns are the y dimension, and "slices" (i.e., `dim(landscapes)[3]`)
#'     indicate separate landscapes.
#'     Values in each cell give the state of the plant:
#'     `0` indicates nothing on plant,
#'     `1` indicates just virus on plant (infectious),
#'     `2` indicates just *Pseudomonas* on plant,
#'     `3` indicates both virus and *Pseudomonas* on plant.
#'     Values < 0 or > 3 are not allowed.
#'     Note that this array is coerced to an array of unsigned integers, so
#'     negative values will become very large integers.
#'     Hence, do not expect an error for negative numbers if you pass them here.
#' @param max_t Single integer giving the maximum time the simulations run.
#' @param N0 Numeric 3D array indicating the starting aphid (non-winged) population
#'     density for each plant and rep.
#'     To indicate separate densities for each plant and/or rep,
#'     the array should have the same dimensions as `landscapes`.
#'     The array can also be 1x1, in which case it's assumed that all plants
#'     and reps start with the same density of aphids.
#' @param W0 Numeric 3D array indicating the starting winged aphid population
#'     density for each plant and rep.
#'     To indicate separate densities for each plant and/or rep,
#'     the array should have the same dimensions as `landscapes`.
#'     The array can also be 1x1, in which case it's assumed that all plants
#'     and reps start with the same density of winged aphids.
#' @param M0 Numeric 3D array indicating the starting mummy population
#'     density for each plant and rep.
#'     To indicate separate densities for each plant and/or rep,
#'     the array should have the same dimensions as `landscapes`.
#'     The array can also be 1x1, in which case it's assumed that all plants
#'     and reps start with the same density of mummies.
#' @param Y0 Numeric vector indicating the starting parasitoid population
#'     density for each rep.
#'     The vector can also be of length 1, in which case it's assumed that
#'     all reps start with the same density of parasitoids.
#' @param insect_ptr External pointer to a C++ object with insect population
#'     information, output from function [make_insects_ptr()].
#' @param disease_ptr External pointer to a C++ object with disease (and
#'     dispersal) information, output from function [make_disease_ptr()].
#' @param wasp_plant_attract Relative attractiveness of plants to wasps.
#'     This affects the proportion of wasps that immigrate from the dispersal
#'     pool to each plant.
#'     It doesn't change the number of wasps that leave plants.
#'     This must be `NULL` or a matrix the same dimensions as each slice
#'     of `landscapes`.
#'     If `NULL`, all plants are equally attractive to wasps.
#'     If a matrix is provided, then the values are divided by their sum
#'     (to make it sum to 1), then those values are used as the proportion of
#'     wasps from the dispersal pool that immigrate to each plant.
#'     Defaults to `NULL`.
#' @param summ Single string to indicate how to summarize output.
#'     If `summ == "none"`, then no summarizing is done, so output is separate
#'     by plant.
#'     If `summ == "time"`, then output is summarized across all plants, so
#'     will only be separated by time and rep.
#'     If `summ == "all"`, then output is summarized across all plants and
#'     time points, so will only be separated by rep.
#'     See "Summarizing" section below for details on output columns.
#'     Defaults to `"none"`.
#' @param infect_time_n Single integer specifying the number of plants
#'     to use when calculating the `infect_time` column when `summ == "all"`.
#'     Ignored when `summ != "all"` except for error checking.
#'     Note that since this is coerced to an unsigned integer, using
#'     a negative number here could cause an error to occur.
#'     Defaults to `0`, which results in at least half the total number of
#'     plants (i.e., `ceiling(prod(dim(landscapes)[1:2]) / 2)`) being used.
#' @param aphid_gone_thresh Single numeric specifying the threshold for aphid
#'     abundance (all stages + parasitized, summed across all plants)
#'     below which it's considered gone when calculating the
#'     `aphid_gone_n` column when `summ == "all"`.
#'     Ignored when `summ != "all"` except for error checking.
#'     Defaults to `1`.
#' @param wasp_gone_thresh Single numeric specifying the threshold for wasp
#'     abundance below which it's considered gone when calculating the
#'     `wasp_gone_n` column when `summ == "all"`.
#'     Ignored when `summ != "all"` except for error checking.
#'     Defaults to `1`.
#' @param infect_stop Single logical for whether to stop simulations
#'     when all plants are infected with virus.
#'     Defaults to `TRUE`.
#' @param out_pseudo Single logical for whether to include *Pseudomonas*
#'     presence in output. Ignored if `summ != "none"`.
#'     Defaults to `FALSE`.
#' @param out_attack_surv Single logical for whether to include aphid survival
#'     from parasitoid attack (weighted mean by abundance for each aphid stage)
#'     in output. Ignored if `summ != "none"`.
#'     Defaults to `FALSE`.
#' @param out_stages Single string for whether and how to separate output for
#'     aphids stage.
#'     If `"none"`, no stages are output.
#'     If `"two"`, adult and juvenile alates and apterous aphids are separated.
#'     If `"all"`, every age stage is separated, typically `29` each for
#'     aphids and alates.
#'     Defaults to `"none"`.
#' @param out_dispersals String for whether / how to output dispersal info.
#'     If `summ %in% c("time", "all")` and `out_dispersals = "all"`,
#'     dispersals are a column list
#'     containing matrices with the number of alate dispersals connecting
#'     plants. The column indicates the plant the alate came from,
#'     and the row indicates the plant the alate dispersed to.
#'     If `summ %in% c("time", "all")` and `out_dispersals = "in"`,
#'     dispersals are a column list
#'     containing matrices with the number of incoming alate dispersals
#'     for each plant. The row indicates plant x coordinate,
#'     and the column indicates y.
#'     If `summ == "none"` and `out_dispersals = "in"`, dispersals are an
#'     integer vector with the number of incoming alate dispersals
#'     for each plant.
#'     Will return an error if `summ == "none"` and `out_dispersals = "all"`.
#'     If `out_dispersals = "none"`, no dispersals are output.
#'     Defaults to `"none"`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Ignored if `dim(landscapes)[3] == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#'
#' @export
#'
#' @return A tibble with columns following the description in the
#' "Summarizing" section.
#'
#'
#' @importFrom tibble as_tibble
#'
#'
sim_plantscape <- function(landscapes, N0, W0, M0, Y0, insect_ptr, disease_ptr, wasp_plant_attract = NULL, max_t = 100L, summ = "none", infect_time_n = 0L, aphid_gone_thresh = 1, wasp_gone_thresh = 1, infect_stop = FALSE, out_pseudo = FALSE, out_attack_surv = FALSE, out_stages = "none", out_dispersals = "none", show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plantscape`, landscapes, N0, W0, M0, Y0, insect_ptr, disease_ptr, wasp_plant_attract, max_t, summ, infect_time_n, aphid_gone_thresh, wasp_gone_thresh, infect_stop, out_pseudo, out_attack_surv, out_stages, out_dispersals, show_progress, n_threads)
}

#' Simulate field(s) of plant types.
#'
#' Simulate locations of plants of different types
#' (virus-infected or -uninfected, *Pseudomonas*-inhabited or uninhabited)
#' along an evenly spaced grid of integers, where the placement of one
#' target can affect subsequent placement of other targets.
#' Target locations are drawn from all combinations of `1` to
#' `n_x` and `1` to `n_y`.
#'
#' @details # Weighting
#' All `wt_*` parameters refer to how placement of one type of plant
#' (virus-infected or -uninfected, *Pseudomonas*-inhabited or uninhabited)
#' affects the sampling weight of subsequent plants of different types.
#' Weight values above 1 cause neighboring locations to be more likely to be
#' sampled later, while values below 1 cause them to be less likely
#' sampled.
#' These weights apply to all plants directly next to the plant of a given
#' type, and they accrue multiplicatively.
#' For example, if `wt_vp = 2` and *Pseudomonas* was place on a plant at
#' location `1,1` (x,y), then plants at locations `1,1`; `1,2`; `2,2`; and `2,1`
#' would all be twice as likely to be sampled as a location for a virus to be
#' placed later on.
#' In the same situation, if *Pseudomonas* was next placed at location `2,1`,
#' then those same locations would now be four times as likely to be chosen
#' for a virus; locations `3,1` and `3,2` would now be twice as likely.
#'
#'
#' @param n_x Single integer indicating x dimension of search area.
#'     Locations will be drawn from `1` to `n_x`.
#'     Must be at least `2` and less than `1e6`.
#' @param n_y Single integer indicating y dimension of search area.
#'     Locations will be drawn from `1` to `n_y`.
#'     Must be at least `2` and less than `1e6`.
#' @param wt_vv A single number indicating how virus placement
#'     affects subsequent placement of virus.
#'     See section "Weighting" above for how these weights work.
#'     Must be >= 0. Defaults to `1`.
#' @param wt_pp A single number indicating how *Pseudomonas* placement
#'     affects subsequent placement of *Pseudomonas*.
#'     See section "Weighting" above for how these weights work.
#'     Must be >= 0. Defaults to `1`.
#' @param wt_vp A single number indicating how virus placement
#'     affects subsequent placement of *Pseudomonas*.
#'     See section "Weighting" above for how these weights work.
#'     Must be >= 0. Defaults to `1`.
#' @param wt_pv A single number indicating how *Pseudomonas* placement
#'     affects subsequent placement of virus.
#'     See section "Weighting" above for how these weights work.
#'     Must be >= 0. Defaults to `1`.
#' @param n_virus Single integer indicating the number of plants that should
#'     be virus infected. This value must be `>=1` and `<= n_x * n_y`.
#' @param n_pseudo Single integer indicating the number of plants that should
#'     be *Pseudomonas* infected.
#'     This value must be `>=1` and `<= n_x * n_y`.
#' @param n_lands Single integer indicating the number of independent
#'     landscapes to simulate. Each landscape will have a number of samples
#'     per type according to `n_virus` and `n_pseudo`.
#'     Must be `> 0` and `< 1e6`.
#'     Defaults to `1`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Multithreading happens across different landscapes, so this is
#'     ignored if `n_lands == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#' @return A cube where rows indicate the x coordinate, columns indicate the
#'     y coordinate, and slices indicate the landscape number.
#'     For each item,
#'     `0` indicates nothing,
#'     `1` indicates a virus infected plant (no *Pseudomonas*),
#'     `2` indicates a *Pseudomonas*-infected plant (no virus), and
#'     `3` indicates a plant with both virus and *Pseudomonas*.
#'     See [land_cube2list()] for converting this to a list of length `n_lands`,
#'     where each item is a [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
#'
#' @export
#'
sim_plant_types <- function(n_x, n_y, n_virus, n_pseudo, wt_vp = 1, wt_pv = 1, wt_vv = 1, wt_pp = 1, n_lands = 1L, virus_starts = NULL, pseudo_starts = NULL, show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plant_types`, n_x, n_y, n_virus, n_pseudo, wt_vp, wt_pv, wt_vv, wt_pp, n_lands, virus_starts, pseudo_starts, show_progress, n_threads)
}

#' Convert a landscape cube to a list of dataframes.
#'
#' @param land_cube Cube containing landscape info, output from [sim_plant_types()].
#'
#' @return A list of length `dim(land_cube)[3]`, where each item is a
#'     [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
land_cube2list <- function(land_cube) {
    .Call(`_aeonia_land_cube2list`, land_cube)
}

#' Fast nonparametric bootstrapping
#'
#' @param x Vector to bootstrap
#' @param B Number of bootstrapping replicates. Must be `>1` and `< 1e9`.
#'     Defaults to `2000L`.
#' @param alpha Confidence level is `100 * (1 - alpha)` percent.
#'     Defaults to `0.05`.
#'
#' @export
#'
booter <- function(x, B = 2000L, alpha = 0.05) {
    .Call(`_aeonia_booter`, x, B, alpha)
}

make_wasps_ptr <- function(rel_attack, a, k, h, sex_ratio, s_y, zeta, sigma_y, demog_error) {
    .Call(`_aeonia_make_wasps_ptr`, rel_attack, a, k, h, sex_ratio, s_y, zeta, sigma_y, demog_error)
}

make_mummies_ptr <- function(pred_surv, mummy_smooth, extinct_N, mummy_dev_time) {
    .Call(`_aeonia_make_mummies_ptr`, pred_surv, mummy_smooth, extinct_N, mummy_dev_time)
}

