# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a pointer object in which to store insect population info.
#'
#' This pointer is used as an argument to [sim_plantscape()].
#'
#' For parameters that defaults to `NA`, keeping the default results in
#' `pop_info$Z` (where `Z` is the name of the variable) being used.
#' These parameters are mostly from previous studies, but some were
#' estimated for this simpler model from the full one.
#' See `data-raw/pop_info.R` for how these were generated.
#'
#'
#' @param pseudo_surv Single numeric indicating aphid survival from *Pseudomonas*.
#' @param fly_p Single numeric indicating the proportion of alates that fly
#'     off plants each day.
#' @param zeta Constant between 0 and 1 that affects the extent to which
#'     parasitoids respond to aphid density, where 0 results in an even
#'     distribution of parasitoids, and 1 results in a linear relationship
#'     between aphid density and parasitoids.
#'     Defaults to `0`.
#' @param extinct_N Single numeric indicating the extinction threshold.
#'     Defaults to `0`.
#' @param demog_error Single logical for whether to include demographic
#'     stochasticity. Defaults to `FALSE`.
#' @param sigma_x Single numeric indicating the standard deviation
#'     for the lognormal distribution used to generate environmental
#'     stochasticity.
#'     Defaults to `0`.
#' @param surv_j Single numeric indicating aphid juvenile survival.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param surv_a Single numeric indicating aphid adult survival.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param recruit Single numeric indicating aphid recruitment.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param fecund Single numeric indicating aphid fecundity.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param K Single numeric indicating the density dependence of the
#'     aphid population.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param K_p_mult Single numeric indicating the multiplier for parasitized
#'     aphid density dependence (`K_p = K * K_p_mult`).
#'     Defaults to `NA`. See 'Details' for more info.
#' @param s_p Single numeric indicating parasitized aphid daily survival.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param R Single numeric indicating
#'     Defaults to `NA`. See 'Details' for more info.
#' @param trans_ma Single numeric indicating the proportion of mummies that
#'     transition to adult parasitoids each day.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param trans_pm Single numeric indicating the proportion of parasitized
#'     aphids that transition to mummies each day.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param pred_surv Single numeric indicating aphid and mummy mortality due
#'     to generalist predators.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param alate_infl Single numeric for the inflection point for the sigmoid
#'     relationship between aphid density and alate offspring proportion.
#'     The proportion of winged offspring from apterous aphids is
#'     `1 / {1 + 10^((alate_infl - z) * alate_slope)}` where `z` is the total number of
#'     aphids on that plant.
#'     To turn off alate production, set this parameter to `Inf`.
#'     Note: Do NOT set both `alate_infl = Inf` and `alate_slope = 0`
#'     because that'll trigger an error that's put in place because
#'     setting these parameters in this way would result in `NaN` values.
#'     Must be > 0.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param alate_slope Single numeric for the slope for the sigmoid
#'     relationship between aphid density and alate offspring proportion.
#'     See `alate_infl` above for the equation.
#'     Must be > 0.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param alate_max Maximum proportion of offspring that are alates.
#'     This is provided so that you can simulate constant alate proportion
#'     and adjust what that alate proportion is.
#'     If `alate_slope = 0`, then alate proportion is a constant
#'     `alate_max / 2`.
#'     Defaults to `1`.
#' @param a Single numeric indicating the parasitoid attack rate.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param h Single numeric indicating the parasitoid handling time.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param k Single numeric indicating the parasitoid aggregation parameter.
#'     Defaults to `NA`. See 'Details' for more info.
#' @param s_y Single numeric indicating the adult parasitoid daily survival.
#'     Defaults to `NA`. See 'Details' for more info.
#'
#' @export
#'
#' @return An `externalptr` object that points to a C++ object that can
#' be pass to [sim_plantscape()].
#'
make_insect_ptr <- function(pseudo_surv, fly_p, zeta = 0, extinct_N = 0, demog_error = FALSE, sigma_x = 0, surv_j = NA_real_, surv_a = NA_real_, recruit = NA_real_, fecund = NA_real_, K = NA_real_, K_p_mult = NA_real_, s_p = NA_real_, R = as.numeric( c()), trans_ma = NA_real_, trans_pm = NA_real_, pred_surv = NA_real_, alate_infl = NA_real_, alate_slope = NA_real_, alate_max = 1, a = NA_real_, h = NA_real_, k = NA_real_, s_y = NA_real_) {
    .Call(`_aeonia_make_insect_ptr`, pseudo_surv, fly_p, zeta, extinct_N, demog_error, sigma_x, surv_j, surv_a, recruit, fecund, K, K_p_mult, s_p, R, trans_ma, trans_pm, pred_surv, alate_infl, alate_slope, alate_max, a, h, k, s_y)
}

#' Test population dynamics for insects for a set of parameters.
#'
#' This function is just for one plant, so the probability that an
#' alate leaves the plant (argument `fly_p` in [make_insect_ptr()]) is always 1.
#'
#' @inheritParams make_insect_ptr
#' @inheritParams sim_plantscape
#'
#' @export
#'
test_insect_pops <- function(max_t, N0, W0, Y0, pseudo_surv = 1, extinct_N = 0, demog_error = FALSE, sigma_x = 0, surv_j = NA_real_, surv_a = NA_real_, recruit = NA_real_, fecund = NA_real_, K = NA_real_, K_p_mult = NA_real_, s_p = NA_real_, R = as.numeric( c()), trans_ma = NA_real_, trans_pm = NA_real_, pred_surv = NA_real_, alate_infl = NA_real_, alate_slope = NA_real_, alate_max = 1, a = NA_real_, h = NA_real_, k = NA_real_, s_y = NA_real_) {
    .Call(`_aeonia_test_insect_pops`, max_t, N0, W0, Y0, pseudo_surv, extinct_N, demog_error, sigma_x, surv_j, surv_a, recruit, fecund, K, K_p_mult, s_p, R, trans_ma, trans_pm, pred_surv, alate_infl, alate_slope, alate_max, a, h, k, s_y)
}

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_aeonia_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_aeonia_inv_logit`, a)
}

#' Compute stable age distribution from transition matrix.
#'
#' The stable age distribution is the proportion of different stages that
#' is required for the population to grow exponentially.
#'
#' @param L Numeric transition matrix. Must be square.
#'
#' @export
#'
sad_leslie <- function(L) {
    .Call(`_aeonia_sad_leslie`, L)
}

#' Simulation plant landscapes with virus spread.
#'
#' @details # Radius
#' From "The Role of Aphid Behaviour in the Epidemiology of Potato Virus Y:
#' a Simulation Study" by Thomas Nemecek (1993; p. 72), dispersal distances
#' follow a Weibull distribution with shape = 0.6569 and scale = 9.613.
#'
#' The default for the `radius` argument uses the median of this
#' distribution.
#' I'm dividing by 0.75 to convert from meters to plant locations that are
#' 0.75 meters apart (typical spacing for pea):
#' `radius = qweibull(0.5, 0.6569, 9.613) / 0.75`.
#'
#' # Summarizing
#' If `summ == "none"`, `n_x * n_y` rows are output for each rep and time point.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `time`: time point
#' 3.  `x`: plant x coordinate
#' 4.  `y`: plant y coordinate
#' 5.  `pseudo`: plant contains *Pseudomonas* (0 or 1); note: this column isn't
#'     included if `out_pseudo = FALSE`
#' 6.  `virus`: plant infectious with virus (0 or 1)
#' 7.  `aphids`: aphid (non-winged) density
#' 8.  `alates`: alate density
#' 9.  `parasitized`: parasitized aphid density
#' 10. `mummies`: mummy density
#' 11. `wasps`: total parasitoid density (`x` and `y` for this row will be 0)
#'
#' If `summ == "pseudo"`, two rows are output for each rep and time point.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `time`: time point
#' 3. `pseudo`: plant contains *Pseudomonas* (0 or 1)
#' 4. `n`: total plants of this type
#' 5. `virus`: number of plants infectious with virus
#' 6. `aphids`: total aphid (non-winged) density summed across all plants of
#'    this type
#' 7. `alates`: total alate density summed across all plants of this type
#' 8. `parasitized`: total parasitized aphid density summed across all plants
#'    of this type
#' 9. `mummies`: total mummy density summed across all plants of this type
#' 10.`wasps`:  total parasitoid density (`type` for this row will be `2`)
#'
#' If `summ == "time"`, one row is output per rep and time point.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `time`: time point
#' 3. `virus`: number of plants infectious with virus
#' 4. `aphids`: total aphid (non-winged) density summed across all plants
#' 5. `alates`: total alate density summed across all plants
#' 6. `parasitized`: total parasitized aphid density summed across all plants
#' 7. `mummies`: total mummy density summed across all plants
#' 8. `wasps` total parasitoid density
#'
#' If `summ == "all"`, one row is output per rep.
#' The columns are...
#' 1.  `rep`: repetition number
#' 2.  `p_alates`: mean total alates / total aphids
#' 3.  `log_aphids`: mean log(aphids+1)
#' 4.  `aphids`: mean aphids
#' 5.  `log_alates`: mean log(alates+1)
#' 6.  `alates`: mean alates
#' 7.  `log_alates`: mean log(parasitized aphids+1)
#' 8.  `alates`: mean parasitized aphids
#' 9.  `log_mummies`: mean log(mummies+1)
#' 10. `mummies`: mean mummies
#' 11. `log_wasps`: mean log(wasps+1)
#' 12. `wasps`: mean wasps
#' 13. `infect_time`: time it took to have `infect_time_n` plants infected
#' 14. `outbreak_size`: maximum number of plants infected with virus
#'
#'
#'
#'
#' @param landscapes Integer cube with the types of each plant in each
#'     landscape. It's assumed that rows are x the dimension,
#'     columns are the y dimension, and "slices" (i.e., `dim(landscapes)[3]`)
#'     indicate separate landscapes.
#'     Values in each cell give the state of the plant:
#'     `0` indicates nothing on plant,
#'     `1` indicates just virus on plant (infectious),
#'     `2` indicates just *Pseudomonas* on plant,
#'     `3` indicates both virus and *Pseudomonas* on plant.
#'     Values < 0 or > 3 are not allowed.
#'     Note that this array is coerced to an array of unsigned integers, so
#'     negative values will become very large integers.
#'     Hence, do not expect an error for negative numbers if you pass them here.
#' @param max_t Single integer giving the maximum time the simulations run.
#' @param insect_ptr External pointer to a C++ object with insect population
#'     information, output from function [make_insect_ptr()].
#' @param N0 Numeric 3D array indicating the starting aphid (non-winged) population
#'     density for each plant and rep.
#'     To indicate separate densities for each plant and/or rep,
#'     the array should have the same dimensions as `landscapes`.
#'     The array can also be 1x1, in which case it's assumed that all plants
#'     and reps start with the same density of aphids.
#' @param W0 Numeric 3D array indicating the starting winged aphid population
#'     density for each plant and rep.
#'     To indicate separate densities for each plant and/or rep,
#'     the array should have the same dimensions as `landscapes`.
#'     The array can also be 1x1, in which case it's assumed that all plants
#'     and reps start with the same density of winged aphids.
#' @param Y0 Numeric vector indicating the starting parasitoid population
#'     density for each rep.
#'     The vector can also be of length 1, in which case it's assumed that
#'     all reps start with the same density of parasitoids.
#' @param virus_attract Effect of virus infection on alate alighting.
#'     Sampling weights for virus-infectious plants is `virus_attract`,
#'     compared to empty (no virus or *Pseudomonas*) plants whose weight is 1.
#'     Thus, when `virus_attract > 1`, alates are attracted to virus-infectious
#'     plants, while `virus_attract < 1` causes them to be repelled by
#'     virus-infectious plants.
#'     Values must be `> 0`.
#' @param pseudo_repel Effect of *Pseudomonas* infection on alate alighting.
#'     Sampling weights for *Pseudomonas*-containing plants is
#'     `1 / pseudo_repel` (note difference from `virus_attract`, hence the
#'     different names!), compared to empty (no virus or *Pseudomonas*)
#'     plants whose weight is 1.
#'     Thus, when `pseudo_repel > 1`, alates are repelled by
#'     *Pseudomonas*-containing plants,
#'     while `pseudo_repel < 1` causes them to be attracted to
#'     *Pseudomonas*-containing plants.
#'     Values must be `> 0`.
#' @param epsilon Effect of virus infection on alate acceptance.
#'     Values `> 1` cause alates to be more likely to stay and feed
#'     (indefinitely) on virus-infected plants,
#'     while values `< 1` cause them to be less likely to stay and feed on
#'     virus-infected plants.
#'     Values must be `> 0`, and `epsilon * w` must be `< 1`.
#' @param p_load_alate Single numeric indicating the probability that an
#'     uninoculated alate is loaded with a virus if it interacts with an
#'     inoculated plant.
#' @param p_load_plant Single numeric indicating the probability that an
#'     uninoculated plant is loaded with a virus if it interacts with an
#'     inoculated alate.
#' @param total_exp_days Single integer indicating the number of days required
#'     for a plant to transition from exposed (inoculated with virus but
#'     not able to pass it on) to infectious (able to infect other plants).
#'     A value of `0` means that an alate inoculating a plant causes that
#'     plant to be infectious the same day.
#'     Because this is not realistic and computationally troublesome,
#'     only values `>1` are allowed.
#'     Defaults to `7`, which is based on the paper "Cucumber mosaic virus
#'     isolates seedborne in *Phaseolus vulgaris*: serology, host-pathogen
#'     relationships, and seed transmission" (Davis & Hampton, 1986).
#' @param w Probability that an alate accepts a plant, meaning that
#'     it stays to feed on it indefinitely.
#'     Must be `> 1e-4` and `< 1`.
#'     The lower limit is because a very small value of `w` causes alates to
#'     fly to so many plants that it becomes computationally problematic.
#'     This is the same reason that I check for (and return and error) if
#'     `w*epsilon < 1e-4`.
#'     Defaults to `0.2`.
#' @param radius Max distance that alates will travel between plants.
#'     Defaults to `7.336451`, which is based on previous work.
#'     See "Radius" section below for details.
#' @param wasp_plant_attract Relative attractiveness of plants to wasps.
#'     This affects the proportion of wasps that immigrate from the dispersal
#'     pool to each plant.
#'     It doesn't change the number of wasps that leave plants.
#'     This must be `NULL` or a matrix the same dimensions as each slice
#'     of `landscapes`.
#'     If `NULL`, all plants are equally attractive to wasps.
#'     If a matrix is provided, then the values are divided by their sum
#'     (to make it sum to 1), then those values are used as the proportion of
#'     wasps from the dispersal pool that immigrate to each plant.
#'     Defaults to `NULL`.
#' @param summ Single string to indicate how to summarize output.
#'     If `summ == "none"`, then no summarizing is done, so output is separate
#'     by plant.
#'     If `summ == "pseudo"`, then output is summarized by whether plants
#'     contain *Pseudomonas*.
#'     If `summ == "time"`, then output is summarized across all plants, so
#'     will only be separated by time and rep.
#'     If `summ == "all"`, then output is summarized across all plants and
#'     time points, so will only be separated by rep.
#'     See "Summarizing" section below for details on output columns.
#'     Defaults to `"none"`.
#' @param infect_time_n Single integer specifying the number of plants
#'     to use when calculating the `infect_time` column when `summ == "all"`.
#'     Ignored when `summ != "all"` except for error checking.
#'     Note that since this is coerced to an unsigned integer, using
#'     a negative number here could cause an error to occur.
#'     Defaults to `0`, which results in the total number of plants
#'     (i.e., `prod(dim(landscapes)[1:2])`) being used.
#' @param infect_stop Single logical for whether to stop simulations
#'     when all plants are infected with virus.
#'     Defaults to `TRUE`.
#' @param out_pseudo Single logical for whether to include *Pseudomonas*
#'     presence in output. Ignored if `summ != "none"`.
#'     Defaults to `FALSE`.
#' @param out_stages Single logical for whether to separate output for aphids
#'     by juvenile vs adults.
#'     Defaults to `FALSE`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Ignored if `dim(landscapes)[3] == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#'
#' @export
#'
#' @return A tibble with columns following the description in the
#' "Summarizing" section.
#'
#'
#' @importFrom tibble as_tibble
#'
#'
sim_plantscape <- function(landscapes, max_t, insect_ptr, N0, W0, Y0, virus_attract, pseudo_repel, epsilon, p_load_alate, p_load_plant, total_exp_days = 7L, w = 0.2, radius = 7.336451, wasp_plant_attract = NULL, summ = "none", infect_time_n = 0L, infect_stop = TRUE, out_pseudo = FALSE, out_stages = FALSE, show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plantscape`, landscapes, max_t, insect_ptr, N0, W0, Y0, virus_attract, pseudo_repel, epsilon, p_load_alate, p_load_plant, total_exp_days, w, radius, wasp_plant_attract, summ, infect_time_n, infect_stop, out_pseudo, out_stages, show_progress, n_threads)
}

#' Simulate field(s) of plant types.
#'
#' Simulate locations of plants of different types
#' (virus-infected or -uninfected, *Pseudomonas*-infected or uninfected)
#' along an evenly spaced grid of integers, where the placement of one
#' target can affect subsequent placement of other targets.
#' Target locations are drawn from all combinations of `1` to
#' `n_x` and `1` to `n_y`.
#'
#'
#' @param n_x Single integer indicating x dimension of search area.
#'     Locations will be drawn from `1` to `n_x`.
#'     Must be at least `2` and less than `1e6`.
#' @param n_y Single integer indicating y dimension of search area.
#'     Locations will be drawn from `1` to `n_y`.
#'     Must be at least `2` and less than `1e6`.
#' @param wt_mat Square numeric matrix indicating how sample weighting on
#'     neighboring locations is affected by a target of each type being
#'     placed in a particular spot.
#'     Item `wt_mat[i,j]` indicates the effect of target type `i` on
#'     subsequent samplings of target type `j`.
#'     Values above 1 cause neighboring locations to be more likely to be
#'     sampled later, while values below 1 cause them to be less likely
#'     sampled.
#'     For locations that have been adjusted using `wt_mat` multiple times,
#'     the weights are multiplied by each other
#'     (e.g., `w *= wt_mat[1,3]` at time `t`, then
#'     `w *= wt_mat[1,2]` at time `t+1`).
#'     All weights start with values of `1`.
#'     The matrix should have the same number of rows and columns as the
#'     number of target types.
#' @param n_virus Single integer indicating the number of plants that should
#'     be virus infected. This value must be `>=1` and `<= n_x * n_y`.
#' @param n_pseudo Single integer indicating the number of plants that should
#'     be *Pseudomonas* infected.
#'     This value must be `>=1` and `<= n_x * n_y`.
#' @param n_lands Single integer indicating the number of independent
#'     landscapes to simulate. Each landscape will have a number of samples
#'     per type according to `n_virus` and `n_pseudo`.
#'     Must be `> 0` and `< 1e6`.
#'     Defaults to `1`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Multithreading happens across different landscapes, so this is
#'     ignored if `n_lands == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#' @return A cube where rows indicate the x coordinate, columns indicate the
#'     y coordinate, and slices indicate the landscape number.
#'     For each item,
#'     `0` indicates nothing,
#'     `1` indicates a virus infected plant (no *Pseudomonas*),
#'     `2` indicates a *Pseudomonas*-infected plant (no virus), and
#'     `3` indicates a plant with both virus and *Pseudomonas*.
#'     See [land_cube2list()] for converting this to a list of length `n_lands`,
#'     where each item is a [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
#'
#' @export
#'
sim_plant_types <- function(n_x, n_y, wt_mat, n_virus, n_pseudo, n_lands = 1L, show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plant_types`, n_x, n_y, wt_mat, n_virus, n_pseudo, n_lands, show_progress, n_threads)
}

#' Convert a landscape cube to a list of dataframes.
#'
#' @param land_cube Cube containing landscape info, output from [sim_plant_types()].
#'
#' @return A list of length `dim(land_cube)[3]`, where each item is a
#'     [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
land_cube2list <- function(land_cube) {
    .Call(`_aeonia_land_cube2list`, land_cube)
}

