# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a pointer object in which to store insect population info.
#'
#' This pointer is used as an argument to [sim_plantscape()].
#'
#'
#' @param B Single numeric indicating the effect of *Pseudomonas* on aphid
#'     population growth.
#' @param fly_p Single numeric indicating the proportion of alates that fly
#'     off plants each day.
#' @param wasp_d_p Single numeric indicating the proportion of adult
#'     parasitoids that are added to the dispersal pool each day.
#'     Defaults to `0`.
#' @param disaster_p Single numeric indicating the probability of disaster
#'     each day. Defaults to `0`.
#' @param disaster_s Single numeric indicating disaster survival.
#'     Defaults to `0`.
#' @param disaster_p Single numeric indicating the probability of disaster
#'     each day. Defaults to `0`.
#' @param extinct_N Single numeric indicating the extinction threshold.
#'     Defaults to `0`.
#' @param demog_error Single logical for whether to include demographic
#'     stochasticity. Defaults to `FALSE`.
#' @param sigma_x Single numeric indicating the standard deviation
#'     for the lognormal distribution used to generate environmental
#'     stochasticity.
#'     Defaults to `0`.
#' @param surv_j Single numeric indicating aphid juvenile survival.
#'     Defaults to `NA`, which results in `pop_info$surv_j` being used.
#'     This is from a previous study.
#' @param surv_a Single numeric indicating aphid adult survival.
#'     Defaults to `NA`, which results in `pop_info$surv_a` being used.
#'     This is from a previous study.
#' @param recruit Single numeric indicating aphid recruitment.
#'     Defaults to `NA`, which results in `pop_info$recruit` being used.
#'     This is from a previous study.
#' @param fecund Single numeric indicating aphid fecundity.
#'     Defaults to `NA`, which results in `pop_info$fecund` being used.
#'     This is from a previous study.
#' @param K Single numeric indicating the carrying capacity (not including
#'     natural enemies or *Pseudomonas*) of the aphid population.
#'     Defaults to `NA`, which results in `pop_info$K` being used.
#'     This is from a previous study.
#' @param alate_0 Single numeric.
#'     The proportion of winged offspring from apterous aphids is
#'     `inv_logit(alate_0 + alate_1 * z)` where `z` is the total number of
#'     aphids on that plant.
#'     Defaults to `NA`, which results in `pop_info$alate_0` being used.
#'     This is from a previous study.
#' @param alate_1 Single numeric affecting how strongly aphid density
#'     influences alate production. See `alate_0` above for the equation.
#'     Defaults to `NA`, which results in `pop_info$alate_1` being used.
#'     This is from a previous study.
#' @param a Single numeric indicating the natural enemy attack rate.
#' @param h Single numeric indicating the natural enemy handling time.
#' @param k Single numeric indicating the natural enemy aggregation parameter.
#' @param s Single numeric indicating the natural enemy daily survival.
#'
#' @export
#'
make_insect_ptr <- function(B, fly_p, wasp_d_p = 0, disaster_p = 0, disaster_s = 0, extinct_N = 0, demog_error = FALSE, sigma_x = 0, surv_j = NA_real_, surv_a = NA_real_, recruit = NA_real_, fecund = NA_real_, K = NA_real_, alate_0 = NA_real_, alate_1 = NA_real_, a = NA_real_, h = NA_real_, k = NA_real_, s = NA_real_) {
    .Call(`_aeonia_make_insect_ptr`, B, fly_p, wasp_d_p, disaster_p, disaster_s, extinct_N, demog_error, sigma_x, surv_j, surv_a, recruit, fecund, K, alate_0, alate_1, a, h, k, s)
}

#' Test population dynamics for insects for a set of parameters.
#'
#' This function is just for one plant, so the probability that an
#' alate leaves the plant (argument `fly_p` in [make_insect_ptr()]) is always 1.
#'
#' @inheritParams make_insect_ptr
#' @inheritParams sim_plantscape
#'
#' @export
#'
test_insect_pops <- function(max_t, A0, W0, P0, B, disaster_p = 0, disaster_s = 0, extinct_N = 0, demog_error = FALSE, sigma_x = 0, surv_j = NA_real_, surv_a = NA_real_, recruit = NA_real_, fecund = NA_real_, K = NA_real_, alate_0 = NA_real_, alate_1 = NA_real_, a = NA_real_, h = NA_real_, k = NA_real_, s = NA_real_) {
    .Call(`_aeonia_test_insect_pops`, max_t, A0, W0, P0, B, disaster_p, disaster_s, extinct_N, demog_error, sigma_x, surv_j, surv_a, recruit, fecund, K, alate_0, alate_1, a, h, k, s)
}

#' Logit and inverse logit functions.
#'
#'
#' @export
#'
logit <- function(p) {
    .Call(`_aeonia_logit`, p)
}

#' @describeIn logit
#'
#' @export
#'
inv_logit <- function(a) {
    .Call(`_aeonia_inv_logit`, a)
}

#' Simulation plant landscapes with virus spread.
#'
#' @details # Radius
#' From "The Role of Aphid Behaviour in the Epidemiology of Potato Virus Y:
#' a Simulation Study" by Thomas Nemecek (1993; p. 72), dispersal distances
#' follow a Weibull distribution with shape = 0.6569 and scale = 9.613.
#'
#' The default for the `radius` argument uses the median of this
#' distribution.
#' I'm dividing by 0.75 to convert from meters to plant locations that are
#' 0.75 meters apart (typical spacing for pea):
#' `radius = qweibull(0.5, 0.6569, 9.613) / 0.75`.
#'
#' @param landscapes Integer cube with the types of each plant in each
#'     landscape. It's assumed that rows are x the dimension,
#'     columns are the y dimension, and "slices" (i.e., `dim(landscapes)[3]`)
#'     indicate separate landscapes.
#' @param max_t Single integer giving the maximum time the simulations run.
#' @param insect_ptr External pointer to a C++ object with insect population
#'     information, output from function [make_insect_ptr()].
#' @param A0 Numeric matrix indicating the starting aphid (non-winged) population
#'     density for each plant.
#'     To indicate separate densities for each plant, the matrix should
#'     have the same number of rows and columns as `landscapes`.
#'     The matrix can also be 1x1, in which case it's assumed that all plants
#'     start with the same density of aphids.
#' @param W0 Numeric matrix indicating the starting winged aphid population
#'     density for each plant.
#'     To indicate separate densities for each plant, the matrix should
#'     have the same number of rows and columns as `landscapes`.
#'     The matrix can also be 1x1, in which case it's assumed that all plants
#'     start with the same density of winged aphids.
#' @param P0 Numeric matrix indicating the starting predator population
#'     density for each plant.
#'     To indicate separate densities for each plant, the matrix should
#'     have the same number of rows and columns as `landscapes`.
#'     The matrix can also be 1x1, in which case it's assumed that all plants
#'     start with the same density of predators.
#' @param alpha Effect of virus infection on alate alighting.
#'     Values `> 0` cause alates to be attracted to virus-infected plants,
#'     while values `< 0` cause them to be repelled by virus-infected plants.
#' @param beta Effect of *Pseudomonas* infection on alate alighting.
#'     Values `> 0` cause alates to be attracted to *Pseudomonas*-infected plants,
#'     while values `< 0` cause them to be repelled by *Pseudomonas*-infected plants.
#' @param epsilon Effect of virus infection on alate acceptance.
#'     Values `> 1` cause alates to be more likely to stay and feed
#'     (indefinitely) on virus-infected plants,
#'     while values `< 1` cause them to be less likely to stay and feed on
#'     virus-infected plants.
#'     Values must be `> 0`, and `epsilon * w` must be `< 1`.
#' @param delta_a Single numeric indicating the probability that an
#'     uninoculated alate is loaded with a virus if it interacts with an
#'     inoculated plant.
#' @param delta_p Single numeric indicating the probability that an
#'     uninoculated plant is loaded with a virus if it interacts with an
#'     inoculated alate.
#' @param total_exp_days Single integer indicating the number of days required
#'     for a plant to transition from exposed (inoculated with virus but
#'     not able to pass it on) to infectious (able to infect other plants).
#'     A value of `0` means that an alate inoculating a plant causes that
#'     plant to be infectious the same day.
#'     Because this is not realistic and computationally troublesome,
#'     only values `>1` are allowed.
#'     Defaults to `7`, which is based on the paper "Cucumber mosaic virus
#'     isolates seedborne in *Phaseolus vulgaris*: serology, host-pathogen
#'     relationships, and seed transmission" (Davis & Hampton, 1986).
#' @param w Probability that an alate accepts a plant, meaning that
#'     it stays to feed on it indefinitely.
#'     Must be `> 1e-4` and `< 1`.
#'     The lower limit is because a very small value of `w` causes alates to
#'     fly to so many plants that it becomes computationally problematic.
#'     This is the same reason that I check for (and return and error) if
#'     `w*epsilon < 1e-4`.
#'     Defaults to `0.2`.
#' @param radius Max distance that alates will travel between plants.
#'     Defaults to `7.336451`, which is based on previous work.
#'     See "Radius" section below for details.
#' @param summ Single string to indicate how to summarize output.
#'     If `summ == "none"`, then no summarizing is done, so output is separate
#'     by plant.
#'     If `summ == "pseudo"`, then output is summarized by whether plants
#'     contain *Pseudomonas*.
#'     If `summ == "all"`, then output is summarized across all plants
#'     will only be separated by time and rep.
#'     Defaults to `"none"`.
#' @param infect_stop Single logical for whether to stop simulations
#'     when all plants are infected with virus.
#'     Defaults to `TRUE`.
#' @param out_pseudo Single logical for whether to include *Pseudomonas*
#'     presence in output. Ignored if `summ != "none"`.
#'     Defaults to `FALSE`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Ignored if `dim(landscapes)[3] == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#'
#' @export
#'
sim_plantscape <- function(landscapes, max_t, insect_ptr, A0, W0, P0, alpha, beta, epsilon, delta_a, delta_p, total_exp_days = 7L, w = 0.2, radius = 7.336451, summ = "none", infect_stop = TRUE, out_pseudo = FALSE, show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plantscape`, landscapes, max_t, insect_ptr, A0, W0, P0, alpha, beta, epsilon, delta_a, delta_p, total_exp_days, w, radius, summ, infect_stop, out_pseudo, show_progress, n_threads)
}

#' Simulate field(s) of plant types.
#'
#' Simulate locations of plants of different types
#' (virus-infected or -uninfected, *Pseudomonas*-infected or uninfected)
#' along an evenly spaced grid of integers, where the placement of one
#' target can affect subsequent placement of other targets.
#' Target locations are drawn from all combinations of `1` to
#' `n_x` and `1` to `n_y`.
#'
#'
#' @param n_x Single integer indicating x dimension of search area.
#'     Locations will be drawn from `1` to `n_x`.
#'     Must be at least `2` and less than `1e6`.
#' @param n_y Single integer indicating y dimension of search area.
#'     Locations will be drawn from `1` to `n_y`.
#'     Must be at least `2` and less than `1e6`.
#' @param wt_mat Square numeric matrix indicating how sample weighting on
#'     neighboring locations is affected by a target of each type being
#'     placed in a particular spot.
#'     Item `wt_mat[i,j]` indicates the effect of target type `i` on
#'     subsequent samplings of target type `j`.
#'     Values above 1 cause neighboring locations to be more likely to be
#'     sampled later, while values below 1 cause them to be less likely
#'     sampled.
#'     For locations that have been adjusted using `wt_mat` multiple times,
#'     the weights are multiplied by each other
#'     (e.g., `w *= wt_mat[1,3]` at time `t`, then
#'     `w *= wt_mat[1,2]` at time `t+1`).
#'     All weights start with values of `1`.
#'     The matrix should have the same number of rows and columns as the
#'     number of target types.
#' @param n_virus Single integer indicating the number of plants that should
#'     be virus infected. This value must be `>=1` and `<= n_x * n_y`.
#' @param n_pseudo Single integer indicating the number of plants that should
#'     be *Pseudomonas* infected.
#'     This value must be `>=1` and `<= n_x * n_y`.
#' @param n_lands Single integer indicating the number of independent
#'     landscapes to simulate. Each landscape will have a number of samples
#'     per type according to `n_virus` and `n_pseudo`.
#'     Must be `> 0` and `< 1e6`.
#'     Defaults to `1`.
#' @param show_progress Single logical for whether to show progress bar.
#'     Defaults to `FALSE`.
#' @param n_threads Single integer for the number of threads to use.
#'     Multithreading happens across different landscapes, so this is
#'     ignored if `n_lands == 1`.
#'     Defaults to `0L`, in which case it takes the value from
#'     `options("mc.cores")` if assigned, and `1L` if not assigned.
#'
#' @return A cube where rows indicate the x coordinate, columns indicate the
#'     y coordinate, and slices indicate the landscape number.
#'     For each item,
#'     `0` indicates nothing,
#'     `1` indicates a virus infected plant (no *Pseudomonas*),
#'     `2` indicates a *Pseudomonas*-infected plant (no virus), and
#'     `3` indicates a plant with both virus and *Pseudomonas*.
#'     See [land_cube2list()] for converting this to a list of length `n_lands`,
#'     where each item is a [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
#'
#' @export
#'
sim_plant_types <- function(n_x, n_y, wt_mat, n_virus, n_pseudo, n_lands = 1L, show_progress = FALSE, n_threads = 0L) {
    .Call(`_aeonia_sim_plant_types`, n_x, n_y, wt_mat, n_virus, n_pseudo, n_lands, show_progress, n_threads)
}

#' Convert a landscape cube to a list of dataframes.
#'
#' @param land_cube Cube containing landscape info, output from [sim_plant_types()].
#'
#' @return A list of length `dim(land_cube)[3]`, where each item is a
#'     [`tibble`][tibble::tbl_df] with columns
#'     `x`, `y`, and `type`.
#'
land_cube2list <- function(land_cube) {
    .Call(`_aeonia_land_cube2list`, land_cube)
}

